---
title: "Homework 10/03/2020"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)



```
```{r}
names(women_data)
```

```{r}

women_data <- read_csv("data/women_in_gov.csv", skip = 4)
dim(women_data)
unique(women_data$x64)
unique(women_data$indicator_name) 
unique(women_data$indicator_code)
unique(women_data$x1960)

women_data_clean <- women_data %>% 
  clean_names() %>% 
  select(
    -c(#x64, 
       indicator_name, indicator_code, x1960, x1961, x1962, x1963, x1964, x1965, x1966, x1967, x1968, x1969, x1970, x1971, x1972, x1973, x1974, x1975, x1976, x1977, x1978, x1979, x1980, x1981, x1982, x1983, x1984, x1985, x1986, x1987, x1988, x1989)
         ) %>% 
  pivot_longer(
    x1990:x1991:x1992:x1993:x1994:x1995:x1996:x1997:x1998:x1999:x2000:x2001:x2002:x2003:x2004:x2005:x2006:x2007:x2008:x2009:x2010:x2011:x2012:x2013:x2014:x2015:x2016:x2017:x2018,
    names_to = "year",
    values_to = "prop_women"
  )
```

```{r}

#counts total missing values
women_data_clean %>%
  summarise(count = sum(is.na(prop_women)))

women_data_clean %>%
filter(is.na(prop_women)) %>%
  unique()

#just NAs are present, not other Non Standard Missing Values were observed 


# replace na observations in the monthly_charges column, with the median of that column
women_data_clean_median <- women_data_clean %>%
    mutate(prop_women = replace(prop_women, 
                                    is.na(prop_women), 
                                    median(prop_women, na.rm = TRUE)))

#NA values were replaced by their median to improve dispersion of data


boxplot(women_data_clean_median$prop_women)
```

```{r}
library(outliers)

# get the z-scores for each value in prop_women
prop_women_zscores <- scores(women_data_clean_median$prop_women)

is_outlier <- prop_women_zscores > 3 | prop_women_zscores < -3

women_data_clean_median <- women_data_clean_median %>%
  mutate(is_outlier = is_outlier)


# create a table with only outliers
women_data_clean_median_outliers <- women_data_clean_median %>%
  filter(is_outlier == TRUE)


women_data_clean_median_no_outliers <- women_data_clean_median %>%
  filter(is_outlier == FALSE)

boxplot(women_data_clean_median_outliers$prop_women)

#as they are really far away from the median and seems to have a distribution on their own the outliers data should be analysed separatelly

boxplot(women_data_clean_median_no_outliers$prop_women)
```

```{r}
# calculate least calories
lowest_10_women <- women_data_clean_median_no_outliers %>%
  arrange(prop_women) %>%
  mutate(ranking = min_rank(prop_women)) %>%
  filter(ranking <=10)

# calculate most calories
highest_10_women <- women_data_clean_median_no_outliers %>%
  mutate(ranking = min_rank(desc(prop_women))) %>%
  filter(ranking <=10)

#women have no parliamentary representation in United Arab Emirates
```

```{r}
# calculate least calories
lowest_10_women_outliers <- women_data_clean_median_outliers %>%
  arrange(prop_women) %>%
  mutate(ranking = min_rank(prop_women)) %>%
  filter(ranking <=10)

# calculate most calories
highest_10_women_outliers <- women_data_clean_median_outliers %>%
  mutate(ranking = min_rank(desc(prop_women))) %>%
  filter(ranking <=10)

#as the outliers data has its own distribution we can do the same analysis separatelly

#interestingly the highest women proportions are all found in Rwanda
```