---
title: "Homework - May 2nd 2020"
output: html_notebook
---
## Import libraries to be used
```{r }
library(tidyverse)
library(janitor)
library(GGally)
library(fastDummies)
library(ggbiplot)

```

## Imports data and checks it

```{r}
avocado_data <- read.csv("data/avocado.csv") 

avocado_data %>% 
glimpse()

avocado_data %>% 
distinct(type)

```

## Starts Data Wrangling

```{r}


avocado_data_trim <- avocado_data %>% 
  clean_names() %>% 
  select(-date, -x, -region, 
         # -x4046, -x4225, -x4770, 
         -total_volume,
         -total_bags) %>% 
  rename(hass_small_4046 = x4046, hass_large_4225 = x4225, hass_xl_4770 = x4770) %>% 
  drop_na()

avocado_data_trim %>% 
  glimpse

avocado_data_trim %>% 
  distinct(average_price) %>%  #259 different prices in total 
  arrange(desc(average_price)) #from 3.25 to 0.44

avocado_data %>% 
distinct(region) #there is 54 regions
```
## Observes data for average_price by different variables

Year:
```{r}
avocado_data_trim %>% 
  group_by(year) %>% 
  ggplot() +
  geom_boxplot(aes(
    x = year,
    y = average_price,
    group = year
  ))
```

Type:

```{r}
avocado_data_trim %>% 
  group_by(type) %>% 
  ggplot() +
  geom_boxplot(aes(
    x = type,
    y = average_price,
    group = type
  ))
```

Total Volume

```{r}
avocado_data_trim %>% 
  # group_by(year) %>% 
  ggplot() +
  geom_point(aes(
    x = total_volume, #has no clear correlation with price determination
    y = average_price,
    colour = type
  ))
```

price/size
```{r}
avocado_data_trim %>% 
  # group_by(year) %>% 
  ggplot() +
  aes(
    y = average_price,) +
  geom_point(aes(
    x = hass_small_4046
  ), colour = "light green") +
  geom_point(aes(
    x = hass_large_4225
  ), colour = "blue") +
  geom_point(aes(
    x = hass_xl_4770
  ), colour = "dark green") 
```

price/bags

```{r}
avocado_data_trim %>% 
  # group_by(year) %>% 
  ggplot() +
  aes(
    y = average_price,) +
  geom_point(aes(
    x = small_bags
  ), colour = "light blue") +
  geom_point(aes(
    x = large_bags
  ), colour = "red") +
  geom_point(aes(
    x = x_large_bags
  ), colour = "purple") #x_large_bags has no much correlation with average_price
```



##Starts creating model

Creates a PCA model

```{r}
# run PCA 
avocados_pca <- avocado_data_trim %>% 
  mutate(type = ifelse(type == "conventional", 0 , 1)) %>% #transforms type into binary variables to be use in pca model
   # select(-type) %>% 
  prcomp(center = TRUE, scale. = TRUE)

summary(avocados_pca)
```

plots avocado_pca

```{r}
ggbiplot(avocados_pca, obs.scale = 1, var.scale = 1)
```


```{r}
avocado_data_trim %>% 
  ggpairs(aes(colour = type))
```
Checks correlation
```{r}
avocado_data_trim %>% 
  ggcorr()
```
Models for average price to be tried by year and type
```{r}
mod1a <- lm(average_price ~ type, data = avocado_data_trim)

mod1b <- lm(average_price ~ year, data = avocado_data_trim)

summary(mod1a) #R^2 = 0.3793

summary(mod1b) #R^2 = 0.008686
```

plot models

```{r}
# set our plotting parameter limits (2x2 graph)
par(mfrow = c(2, 2)) 

# plot
plot(mod1a)
```

```{r}
# set our plotting parameter limits (2x2 graph)
par(mfrow = c(2, 2)) 

# plot
plot(mod1b)
```

